### ISSUE TITLE
Implementation with IdentityFile login

### ISSUE THREAD

**Issue by juanjq** [nicolaschotard/stackyter#17]
I'm trying to use this with a jump in the host that is connected automatically via IdentityFile option in the ssh configuration e.g.

```
Host server
   User username
   HostName ip
   IdentityFile ~/.ssh/identity
   Proxyjump other.jump
```

How can I implement this in the configuration file for stckyter? In order to get the "key" form the identity file I have saved, to not input the password manually.

**Comment by airnandez** [comment]
In your `~/.stackyter.yaml` file you could have something like:

```yaml
my_server:
  host:     'server'
  jupyter:  'lab'
  workdir:  '/my/notebooks/dir'
  runbefore:
    - '/path/to/script/to/run/before/launching/jupyter'
```

and then execute `stackyter` with a command like

```bash
$ stackyter.py -c my_server
```

`stackyter.py` will use the `ssh` command to connect to `server` and for doing so it will read the contents of your SSH configuration (typically in `~/.ssh/config`).
